version: '3.4'

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "BancoCarrefour@2024"
        ACCEPT_EULA: "Y"
  api:    
    build:
      context: .
      dockerfile: /API/Dockerfile
    container_name: api
    ports:
     - "4700:8081"    
  api-release:    
    build:
      context: .
      dockerfile: /API-Releases/Dockerfile
    container_name: api-releases
    ports:
     - "4701:8081"
    depends_on:
        - sql-server-db
  api-report:    
    build:
      context: .
      dockerfile: /API-Report/Dockerfile
    container_name: api-report
    ports:
     - "4702:8081"    